#!/bin/bash -v

saved=`pwd`
mkdir -p downloads
cd downloads

# install latest chromium
if [ ! -f google-chrome-stable_current_amd64.deb ]; then
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
fi

# Install chromdriver
if [ ! -f chromedriver_linux64.zip ]; then
  wget https://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip
fi
unzip -qu chromedriver_linux64.zip
sudo mv chromedriver /usr/bin

cd $saved

# install some additional needed packages
sudo apt-get -qq update
sudo apt-get install -y libappindicator1 fonts-liberation
sudo dpkg -i downloads/google-chrome-stable_current_amd64.deb

gem install bundler
bundle install
